-- FIND W/ TELESCOPE KEYMAPS --

local M = {}

M.n = { maps = { name = "+find",
    ["<bs>"] = { "<cmd>FzfLua resume<CR>", "fzf reusme"},
    ["<tab>"] = { "<cmd>Telescope buffers theme=dropdown<CR>", "<tab>"},
    ["<CR>"]  = { "<cmd>Telescope resume<CR>", "resume"},
    ["<c-space>"] = { "<CMD>FzfLua live_grep<CR>"},
    ["0"]  = { "<cmd>Telescope resume<CR>", "resume"},
    ["-"] = { "<cmd>Telescope zoxide list<CR>", "zoxide lst"},
    ["."] = { [[<cmd>FzfLua files cwd=<C-r>=expand("%:h")<CR><CR>]], "dotfiles"},
    [","] = { "<cmd>Telescope files theme=dropdown<CR>", "fileb"},
    ["~"] = { "<cmd>Telescope bookmarks theme=dropdown<CR>", "bmarks dropdown"},
    ["`"] = { "<cmd>Telescope pickers<CR>", "pickers"},
    ["!"] = { "<cmd>Telescope builtin<CR>", "builtin"},
    ["_"] = { "<cmd>Telescope ", "<prompt>"},
    ["="] = { "<cmd>SK<CR>", "skim"},
    ["+"] = { "<cmd>SK<CR>", "skim"},
    ["/"] = { 
    name="+grep",
        ["/"] = { "<cmd>Telescope theme=dropdown live_grep<CR>"},
        ["."] = { "<cmd>Telescope theme=dropdown current_buffer_fuzzy_find<CR>"},
        ["<space>"] = { "Telescope grep_string<CR>", "grepstr<CR>"},
    },
    ["G"] = { 
        name = "+code",
        ["/"] = { "<cmd>Telescope theme=dropdown live_grep<CR>"},
        ["."] = { "<cmd>Telescope theme=dropdown current_buffer_fuzzy_find<CR>"},
        ["<space>"] = { "Telescope grep_string", "grepstr<CR>"},
        S = { "Telescope lsp_dynamic_workplace_symbols thmee=dropdown<CR>", "dyn ws sym"},
        s = { "Telescope lsp_workplace_symbols thmee=dropdown<CR>", "ws sym"},
        ["<C-s>"] = { "Telescope symbols thmee=dropdown<CR>", "symbols"},
        l = { "Telescope current_buffer_tags thmee=dropdown<CR>", "curr tags"},

    },
    ["|"] = { "<cmd>Telescope ", "<prompt>"},
    [":"] = { "<cmd>Telescope commands", "cmds"},
    [";"] = { "<cmd>Telescope commands theme=dropdown<CR>", "cmd dropdown"},
    ["?"] = { "<ESC>:Rg<CR>", "rg",},
    ["\\"] = { "<cmd>FzfLua live_grep<CR>", "fd"}, 
    ["<cr>"] = { "<cmd>Telescope reloader theme=dropdown<CR>", "otps"},
    ["<del>"] = { "<cmd>Telescope builtin theme=dropdown<CR>", "otps"},
    ['<BS>'] = {"<CMD>Telescope resume<CR>", "resume"},
    ['<space>'] = {"<CMD>Telescope resume<CR>", "resume"},
    a  = { "<cmd>Telescope autocommands<CR>", "acmd"},
    b = { "<cmd>Telescope buffers theme=dropdown<CR>", "buffers"},
    c = { "<cmd>Telescope lsp_code_actions theme=cursor<CR>", "code actions"},
    x  = { "<cmd>Telescope marks<CR>", "marks"},
    d = { "<cmd>Telescope diagnostics theme=dropdown<CR>", "doc diagnostics"},
    e = { "<cmd>FzfLua files<CR>", "doc diagnostics"},
    f = { "<cmd>FzfLua files<CR>", "doc diagnostics"},
    k = { "<ESC>:Telescope keymaps theme=dropdown<CR>", "maps"},
    K = { "<ESC>:Telescope file_browser path=~/.config/nvim/lua/keymaps<CR>", "map fzf"},
    g = { "<cmd>Telescope live_grep theme=dropdown<cr>", "grep" },
    s = { "<cmd>Telescope lsp_document_symbols<CR>", "symbols"},
    w = { "<CMD>FzfLua files cwd=~/mk<CR>", "wiki"},
    I = { "<CMD>Telescope highlights<CR>", "highlights"},
    t = { "<cmd>Telescope tags theme=dropdown<CR>", "tags"},
    q = { "<cmd>Telescope quickfix theme=dropdown<CR>", "quickfix"},
    l = { "<cmd>Telescope loclist theme=dropdown<CR>", "loclist"},
    o = { "<cmd>Telescope vim_options theme=dropdown<CR>", "vim options"},
    r = { "<cmd>Telescope lsp_references theme=dropdown<CR>", "code refs"},
    T = { "<cmd>Telescope treesitter theme=dropdown<CR>", "TS"},
    i = { "<cmd>Telescope lsp_implementations theme=dropdown<CR>", "code implementations"},
    m = { "<cmd>Telescope bookmarks theme=dropdown<CR>", "bmarks"},
    S = { "<cmd>Telescope lsp_workplace_symbols<CR>", "ws symbols"},
    p = { "<cmd>Telescope picker theme=dropdown<CR>", "projects"},
    j = { "<cmd>Telescope jumplist theme=dropdown<CR>", "jumplist"},
    h = { "<cmd>Telescope help_tags<CR>", "help tags"},
    L = { "<CMD>FzfLua colorschemes<CR>", "colors"},
    z = { "<cmd>Telescope zoxide theme=dropdown<CR>", "zoxide"},
    ["<C-z>"] = { "<cmd>Telescope current_buffer_fuzzy_find theme=cursor<CR>", "code actions"},
    ["<C-j>"] = { "<cmd>Telescope lsp_code_actions theme=cursor<CR>", "code actions"},
    D = { "<cmd>Telescope lsp_definitions theme=dropdown<CR>", "code defs"},
    F = { "<cmd>Telescope file_browser theme=dropdown<CR>", "fd"}, 
    ["<"] = { "<cmd>Telescope grep_string theme=dropdown<cr>", "grep" },
    H = { "<cmd>Telescope highlights<CR>", "highlights"},
    M = { "<cmd>Telescope man_pages<CR>", "man pages"},
    R  = { "<cmd>Telescope registers<CR>", "registers"},
    B  = { "<cmd>Telescope builtin<CR>", "tag_stack"},
    -- x = { ":Cheatsheet<CR>", "csheet"},
    -- X = { ":CheatsheetEdit<CR>", "csheet edit"},
    C = {"<CMD>Telescope themes theme=dropdown "},

},
        opts = {
            noremap = true,
            silent = false,
            mode = "v",
            prefix = "<space>"
        }
}
M.v  = {maps = M.n.maps,
        opts = {
            noremap = true,
            silent = false,
            mode = "v",
            prefix = "<space>"
        }
    }

return M

