-- WIKI CONFIG Local Leader KEYMAPS (,w) --

local M = {}

M.n ={ maps = { name = "+wiki",
    ["<SPACE>"] = { ":e ~/wiki/index.md<CR>", "index" },
    ["<CR>"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope file_browser theme=dropdown path=~/wiki<CR>", "file_browser"},
    ["_"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope file_browser theme=dropdown path=~/wiki<CR>", "file_browser"},

    ["<TAB>"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope file_browser theme=dropdown path=~/wiki<CR>", "file_browser"},
    ["-"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope find_files<CR>", "find_files"},

    [","] = { ":e ~/wiki/index.md<CR><ESC>:Telescope find_files<CR>", "find_files"},
    ["."] = { ":e ~/wiki/index.md<CR><ESC>:Telescope find_files<CR>", "find_files"},

    ["/"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope find_files<CR>", "find_files"},
    [";"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope live_grep<CR>", "live_grep"},
    ["?"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope fd<CR>", "fd"},
    ["\\"] = { ":e ~/wiki/index.md<CR><ESC>:Telescope file_browser theme=dropdown path=~/wiki<CR>", "file_browser"},
    c = { name = "+code",
	["<SPACE>"] = { ":e ~/wiki/dev/index.md<CR>", "index" },
	["-"] = { ":e ~/wiki/dev/index.md<CR><ESC>:Telescope find_files<CR>", "find_files"},
	["/"] = { ":e ~/wiki/dev/index.md<CR><ESC>:Telescope live_grep<CR>", "live_grep"},
	["?"] = { ":e ~/wiki/dev/index.md<CR><ESC>:Telescope fd<CR>", "fd"},
	["."] = { ":e ~/wiki/dev/index.md<CR><ESC>:Telescope file_browser<CR>", "file_browser"},
    },
    i = { ":e ~/wiki/index.md<CR>", "index"},
    j = { ":e ~/wiki/journal.txt<CR>", "journal"},
    a = { ":e ~/wiki/auth/index.md<CR>", "auth"},
    C = { ":e ~/wiki/creds/index.md<CR>", "credentials"},
    V = { ":e ~/wiki/idlets/index.md<CR>", "idlets"},
    I = { ":e ~/wiki/devisa/index.md<CR>", "devisa"},
    x = { ":e ~/wiki/dev/index.md<CR>", "dev"},
    J = { ":e ~/wiki/jobs/index.md<CR>", "jobs"},
    l = { ":e ~/wiki/diary/log/index.md<CR>", "log"},
    n = { ":JournalToday<CR>", "daily note"},
    N = { ":JournalTodayAlt<CR>", "daily note nested"},
    b = { name = "+bookmarks",
	r = { ":e ~/wiki/dev/bookmarks/rust/index.md<CR>", "rust"},
	n = { ":e ~/wiki/dev/bookmarks/nim/index.md<CR>", "nim"},
	z = { ":e ~/wiki/dev/bookmarks/zig/index.md<CR>", "zig"},
	c = { ":e ~/wiki/dev/bookmarks/ccPP/index.md<CR>", "c/c++"},
	s = { ":e ~/wiki/dev/bookmarks/sh/index.md<CR>", "sh"},
	p = { ":e ~/wiki/dev/bookmarks/py/index.md<CR>", "py"},
    },
    s = { name = "+snippets",
	["<SPACE>"] = { ":e ~/wiki/dev/bookmarks/index.md<CR>", "general" },
	["<CR"]     = { name = "+new",
	    r = { ":e ~/wiki/dev/snippets/rust/<CR>", "rust"},
	    n = { ":e ~/wiki/dev/snippets/nim/<CR>", "nim"},
	    z = { ":e ~/wiki/dev/snippets/zig/<CR>", "zig"},
	    c = { ":e ~/wiki/dev/snippets/ccpp<CR>", "c/c++"},
	    s = { ":e ~/wiki/dev/snippets/sh/<CR>", "sh"},
	    p = { ":e ~/wiki/dev/snippets/py/<CR>", "sh"},
	},
	r = { ":e ~/wiki/dev/snippets/rust/snippets/inde.md<CR>", "rust"},
	n = { ":e ~/wik/dev/snippets/nim/index.md<CR>", "nim"},
	z = { ":e ~/wik/dev/snippets/zig/index.md<CR>", "zig"},
	c = { ":e ~/wiki/dev/snippets/ccpp/index.md<CR>", "c/c++"},
	s = { ":e ~/wiki/dev/snippets/sh/index.md<CR>", "sh"},
	p = { ":e ~/wiki/dev/snippets/sh/py.md<CR>", "sh"},
    },
    p = { name = "+projects",
	["<SPACE>"] = { ":e ~/wiki/p/index.md<CR>", "index" },
	["I"] =       { ":e ~/wiki/proj/idwplset/index.md.md<CR>", "index" },
        i = { ":e ~/wiki/proj/ideas/index.md<CR>", "ideas" },
	p =           { ":e ~/wiki/proj/index.md<CR>", "projs" }
    },
    d = { name = "+diary",
	["<SPACE>"] = { ":VimwikiDiaryIndex<CR>", "index" },
	["<CR>"] = { ":VimwikiMakeDiaryNote<CR>", "daily note"},
	["<S-Tab>"] = { ":VimwikiYesterdayMakeDiaryNote<CR>", "yesterday note"},
	["<TAB>"] = { ":VimwikiTomorrowMakeDiaryNote<CR>", "tomorrow note"},
	["-"] = { ":e ~/wiki/diary/diary/index.md CR><ESC>:Telescope fd", "find diary files"},
	["/"] = { ":e ~/wiki/diary/diary/index.md CR><ESC>:Telescope find_files", "live grep"},
	["?"] = { ":e ~/wiki/diary/diary/index.md CR><ESC>:Telescope find_files", "fd"},
	["["] = { ":VimwikiYesterdayMakeDiaryNote<CR>", "yesterday note"},
	["]"] = { ":VimwikiTomorrowMakeDiaryNote<CR>", "tomorrow note"},
	["<"] = { ":VimwikiYesterdayMakeDiaryNote<CR>", "yesterday note"},
	[">"] = { ":VimwikiTomorrowMakeDiaryNote<CR>", "tomorrow note"},
	[","] = { ":VimwikiDiaryPrevDay<CR>", "yesterday note"},
	["."] = { ":VimwikiTomorrowMakeDiaryNote<CR>", "tomorrow note"},
	j = {  ":JournalToday<CR>", 'journal today' },
	J = {  ":JournalTodayAlt<CR>", 'today nested' },
	t = { ":e ~/wiki/templates/vimwiki/diary_entry.md<CR>", "diary template"},
	T = { ":e ~/wiki/templates/diary.tpl<CR>", "diary template"},
	n = { ":VimwikiMakeDiaryNote<CR>", "daily note"},
    },
    t = { name = "+templates", 
	["<SPACE>"] = { ":e ~/wiki/templates/index.md<CR>", "index" },
	b = { ":e ~/wiki/templates/index.md<CR>", "index" },
	["<CR"]     = {name =  "+new",
	    r = { ":e ~/wiki/teampltes/rust/inde.md<CR>", "rust"},
	    n = { ":e ~/wiki/dev/nim/bookmarks/index.md<CR>", "nim"},
	    z = { ":e ~/wiki/dev/zig/bookmarks/index.md<CR>", "zig"},
	    c = { ":e ~/wiki/dev/ccpp/bookmarks/index.md<CR>", "c/c++"},
	    s = { ":e ~/wiki/dev/sh/bookmarks/index.md<CR>", "sh"},
	},
	r = { ":e ~/wiki/dev/rust/snippets/inde.md<CR>", "rust"},
	n = { ":e ~/wiki/dev/nim/bookmarks/index.md<CR>", "nim"},
	z = { ":e ~/wiki/dev/zig/bookmarks/index.md<CR>", "zig"},
	c = { ":e ~/wiki/dev/ccpp/bookmarks/index.md<CR>", "c/c++"},
	s = { ":e ~/wiki/templats/sh/index.md<CR>", "sh"},
	v = { ":e ~/wiki/templats/vimwiki/index.md<CR>", "vimwiki" },
	S = { ":e ~/wiki/templats/svelte/index.md<CR>", "svelte" }
    },
},
    opts = require("keymaps.common").opts.n("w"), 
 }


M.v = {
    maps = M.n.maps,
    opts = require("keymaps.common").opts.v("w"),
}

return M
