-- return { name = "+fzf",
lvim.builtin.which_key.mappings["f"] = {
  name = "+fzf",
  f = { "<CMD>FzfLua files cwd=.<CR>", "files ./" },
  p = { "<CMD>Telescope projects<CR>", "fd proj"},
  h = { "<CMD>FzfLua oldfiles<CR>", "history" },
  d = { "<CMD>FzfLua files cwd=~/.config/<CR>", "dotfiles" },
  ["?"] = { "<CMD>FzfLua files cwd=.<CR>", "files ./" },
  ["<space>"] = { "<cmd>FzfLua files cwd=.<CR>", "files ./" },
  ["/"] = { "<CMD>FzfLua search_history<CR>", "search_history" },
  [";"] = { "<CMD>FzfLua command_history<CR>", "cmd_history" },
  ["_"] = { "<ESC>:FzfLua colorschemes<CR>", "colorschemes" },
  ["="] = { "<ESC>:Telescope builtin", "<prompt>" },
  ["+"] = { "<ESC>:Telescope ", "<prompt>" },
  ["\\"] = { "<ESC>:Telescope ", "<prompt>" },
  ["|"] = { "<ESC>:Telescope ", "<prompt>" },
  ["<BS>"] = { ":Telescope resume theme=dropdown<CR>", "resume" },
  ["<CR>"] = { ":Telescope file_browser theme=dropdown<CR>", "file browser" },
  ["<bs>"] = { "<ESC>:Telescope resume<CR>", "<bs>" },
  ["<tab>"] = { "<ESC>:Telescope buffers theme=dropdown<CR>", "<tab>" },
  [","] = { "<ESC>:Telescope oldlfiles theme=dropdown<CR>", "buffers" },
  ["."] = { "<CMD>FzfLua files cwd=~/.config<CR>", "dotfiles" },
  [">"] = { "<ESC>:Telescope file_browser theme=dropdown<CR>", "fileb" },
  ["~"] = { "<CMD>FzfLua files cwd=~<CR>", "home" },
  ["`"] = { "<ESC>:Telescope pickers<CR>", "pickers" },
  ["-"] = { "<ESC>:FzfLua files cwd=.<CR>", "files ." },
  b = { "<ESC>:Telescope file_browser theme=dropdown<cr>", "file browser" },
  B = { "<ESC>:Telescope bookmarks theme=dropdown<cr>", "file browser" },
  c = { ":Telescope commmands theme=dropdown<CR>", "commands" },
  C = { ":Cheatsheet <CR>", "csheets" },
  Z = { "<ESC>:Telescope find_files theme=dropdown<cr>", "files" },
  -- t = C.tmpl_fzf(),
  z = { "<ESC>:Telescope zoxide theme=dropdown<cr>", "zoxide" },
  L = { name = "+lspconfig",
    ["<space>"] = { "<ESC>:Files $CONF/nvim/nvim-lspsettings<CR>", "FZF" },
    d = { ":e $CONF/nvim/nlsp-settings/denols.json", "deno" },
    Q = { ":e $CONF/nvim/nlsp-settings/codeqlls<CR>", "codeql" },
    r = { ":e $CONF/nvim/nlsp-settings/rust_analyzer<CR>", "rust analyzer" },
    p = { ":e $CONF/nvim/nlsp-settings/pylsp.json<CR>", "pyjson" },
    P = { ":e $CONF/nvim/nlsp-settings/pyright.json<CR>", "pyright" },
    j = { ":e $CONF/nvim/nlsp-settings/jsonls.json<CR>", "jsonls" },
    n = { ":e $CONF/nvim/nlsp-settings/nimls.json<CR>", "nimls" },
    l = { ":e $CONF/nvim/nlsp-settings/sumneko-lua.json<CR>", "sumneko-lua" },
    y = { ":e $CONF/nvim/nlsp-settings/yaml.json<CR>", "yaml" },
    -- ["<tab>"] = C.teled("lsp_status"),
    -- ["<bs>"] = C.teled("lsp_status"),
  },
  F = { "<ESC>:Telescope git_files theme=dropdown<cr>", "git files" },
  M = { ":Telescope man_pages<CR>", "man pages" },
  D = { "<ESC>:Telescope fd theme=dropdown<cr>", "fd" },
  [":"] = { ":Telescope command_palette theme=dropdown<CR>", "cmd palette" },
  H = { ":Telescope help_tags theme=dropdown<CR>", "help tags" },
  g = { "<ESC>:FzfLua live_grep<CR>", "rg", },
  G = { "<ESC>:FzfLua live_grep<CR>", "rg", },
  w = { ":Telescope file_browser theme=dropdown path=~/wiki/<CR>", "wiki fb" },
  v = { name = "+vim",
    n = { ":FzfLua files ~/.config/nvim<CR>", "nvim" },
    v = { ":FzfLua files ~/.config/vim<CR>", "vim" },
  },
  n = { ":Telescope file_browser theme=dropdown path=~/.config/nvim<CR>", "nvim fb" },
  N = { ":Telescope file_browser path=~/.config/nvim<CR>", "nvim fb" },
  s = { "<cmd>Telescope symbols theme=dropdown<CR>", "symbols" },
  T = { "<cmd>Telescope tags theme=dropdown<CR>", "tags" },
  q = { "<cmd>Telescope quickfix theme=dropdown<CR>", "quickfix" },
  r = { "<cmd>Telescope lsp_references theme=dropdown<CR>", "code refs" },
  R = { "<cmd>Telescope treesitter theme=dropdown<CR>", "TS" },
  i = { "<cmd>Telescope lsp_implementations theme=dropdown<CR>", "code implementations" },
  m = { "<cmd>Telescope bookmarks theme=dropdown<CR>", "bmarks" },
  l = { "<cmd>Telescope loclist theme=dropdown<CR>", "loclist" },
  k = { "<cmd>Telescope keymaps<CR>", "keymaps" },
  o = { "<cmd>Telescope vim_options theme=dropdown<CR>", "vim options" },
}
