local utils = require("user.keys.utils")
local u = require "user.util"
local edit = utils.edit
local d= require("user.util").dirs

local ft = { name = "+ft",
  w = { "<CMD>e " .. d.plug .. "vimwiki.lua<CR>", "wiki" },
  W = { "<CMD>e ~/.config/lvim/ftplugin/vimwiki.lua<CR>", "vwiki ftplugin" },
  m = { "<CMD>e ~/.config/lvim/ftplugin/markdown.lua<CR>", "md ftplugin" },
}
local cma_prefix ={ name = "+local",
    a = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/a.lua<CR>", "a" },
    b = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/b.lua<CR>", "b" },
    c = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/c.lua<CR>", "c" },
    d = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/d.lua<CR>", "d" },
    e = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/e.lua<CR>", "e" },
    f = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/f.lua<CR>", "f" },
    g = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/g.lua<CR>", "g" },
    i = { "<CMD>e ~/.config/lvim/lua/user/keys/comma/i.lua<CR>", "i" },
    j = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/j.lua<CR>", "j" },
    m = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/m.lua<CR>", "m" },
    o = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/o.lua<CR>", "o" },
    p = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/p.lua<CR>", "p" },
    q = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/q.lua<CR>", "q" },
    r = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/r.lua<CR>", "r" },
    s = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/s.lua<CR>", "s" },
    t = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/t.lua<CR>", "t" },
    u = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/u.lua<CR>", "u" },
    v = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/v.lua<CR>", "v" },
    w = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/w.lua<CR>", "w" },
    y = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/y.lua<CR>", "x" },
    x = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/x.lua<CR>", "y" },
    z = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/z.lua<CR>", "z" },
  }

local packer = { name = "+plug",
    s = { "<ESC>:PackerSync<CR>" },
    G = { "<ESC>:e ~/.config/lvim/lua/user/plug/copilot.lua<CR>", "copilot" },
    i = { "<ESC>:PackerInstall<CR>" },
    u = { "<ESC>:PackerUpdate<CR>" },
    c = { "<ESC>:PackerCompile<CR>" },
    p = { "<ESC>:e ~/.config/lvim/lua/user/plug.lua<CR>", "config" },
    C = { "<ESC>:PackerClean<CR>" },
    S = { "<ESC>:PackerStatus<CR>" },
    l = { "<ESC>:PackerClean<CR>" },
    L = { "<ESC>:PackerClean<CR>" },
    r = { "<cmd>lua require('lv-utils').reload_lv_config()<cr>", "Reload" }
  }
local keys = { name = "+keys",
    k = { "<CMD>e ~/.config/lvim/lua/user/keys.lua<CR>", "keys" },
    ["<space>"] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc.lua<CR>", "<spc>" },
    ["<cr>"] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/cr.lua<CR>", "crj" },
    ["."] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc.lua<CR>", "leader" },
    [","] = { "<CMD>e ~/.config/lvim/lua/user/keys/comma.lua<CR>", "comma" },
    a = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/a.lua<CR>", "a" },
    b = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/b.lua<CR>", "b" },
    c = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/c.lua<CR>", "c" },
    d = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/d.lua<CR>", "d" },
    e = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/e.lua<CR>", "e" },
    f = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/f.lua<CR>", "f" },
    g = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/g.lua<CR>", "g" },
    h = {  "Nop" },
    i = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/i.lua<CR>", "i" },
    j = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/j.lua<CR>", "j" },
    m = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/m.lua<CR>", "m" },
    n = { "nop"},
    o = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/o.lua<CR>", "o" },
    p = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/p.lua<CR>", "p" },
    q = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/q.lua<CR>", "q" },
    r = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/r.lua<CR>", "r" },
    s = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/s.lua<CR>", "s" },
    t = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/t.lua<CR>", "t" },
    u = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/u.lua<CR>", "u" },
    v = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/v.lua<CR>", "v" },
    w = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/w.lua<CR>", "w" },
    y = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/y.lua<CR>", "x" },
    x = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/x.lua<CR>", "y" },
    z = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/z.lua<CR>", "z" },
    ["F"] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/spc.lua<CR>", "<spc><spc>" },
    ["<C-space>"] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/spc.lua<CR>", "<spc><spc>" },


  }
-- return {

local spc_prefix = { name = "+leader",
    a = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/spc/a.lua<CR>", "a" },
    b = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/b.lua<CR>", "b" },
    c = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/c.lua<CR>", "c" },
    d = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/d.lua<CR>", "d" },
    e = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/e.lua<CR>", "e" },
    f = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/f.lua<CR>", "f" },
    g = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/g.lua<CR>", "g" },
    i = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/i.lua<CR>", "i" },
    j = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/j.lua<CR>", "j" },
    m = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/m.lua<CR>", "m" },
    o = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/o.lua<CR>", "o" },
    p = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/p.lua<CR>", "p" },
    q = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/q.lua<CR>", "q" },
    r = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/r.lua<CR>", "r" },
    s = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/s.lua<CR>", "s" },
    t = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/t.lua<CR>", "t" },
    u = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/u.lua<CR>", "u" },
    v = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/v.lua<CR>", "v" },
    w = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/w.lua<CR>", "w" },
    y = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/y.lua<CR>", "x" },
    x = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/x.lua<CR>", "y" },
    z = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/z.lua<CR>", "z" },
    ["<space>"] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc.lua<CR>", "<SPC> prefix" },
    ["<c-space>"] = { "<CMD>e ~/.config/lvim/lua/user/keys/spc/spc.lua<CR>", "<SPC><SPC>" },
  }
lvim.builtin.which_key.mappings["v"] = {
  L = edit("~/.config/lvim/config.lua", "config"),
  b = { "<ESC>:e ~/.config/lvim/lua/user/abbr.lua<CR>", "abbr"},
  u = { "<ESC>:e ~/.config/lvim/lua/user/util.lua<CR>", "config" },
  c = { "<ESC>:e ~/.config/lvim/lua/user/cmd.lua<CR>", "cmd.lua" },
  a = { "<ESC>:e ~/.config/lvim/lua/user/acmd.lua<CR>", "acmd.lua" },
  N = { "<ESC>:e ~/.config/lvim/lua/user/plug.lua<CR>", "plug.lua" },
  r = { "<ESC>:e ~/.config/lvim/lua/user/color.lua<CR>", "color.lua" },
  n = { "<ESC>:e ~/.config/nvim/init.lua<CR>", "config" },
  C = { "<ESC>:e ~/.config/lvim/config.lua<CR>", "config" },
  P = { "<ESC>:e ~/.config/lvim/lua/user/plug.lua<CR>", "plug.lua" },
  i = { "<ESC>:e ~/.config/lvim/config.lua<CR>", "config.lua" },
  l = { "<ESC>:e ~/.config/lvim/lua/user/lsp.lua<CR>", "lsp.lua" },
  s = { "<ESC>:e ~/.config/lvim/lua/user/opt/nvim.lua<CR>", "settings" },
  v = { "<ESC>:e ~/.config/lvim/lua/user/opt/lvim.lua<CR>", "lvim conf" },
  w = { "<CMD>e ~/.config/lvim/lua/user/plug/vimwiki.lua<CR>", "wiki" }, 
  K = { "<CMD>e ~/.config/lvim/lua/user/keys.lua<CR>", "keys" },
  f = ft,
  ["<space>"] = spc_prefix,
  [","] = cma_prefix,
  k = keys,
  p = packer,
}
