return { name = "+zsh",
  ["<space>"] = { ":e ~/.zshrc<CR>", "zshrc" },
  ["<CR>"] = { ":FzfLua files cwd= ~/.zsh<CR>", "fzf" },
  z = { ":e ~/.zshrc<CR>", "zshrc" },
  c = { ":e ~/.zshrc<CR>", "zshrc" },
  a = { ":e ~/.zsh/aliases.zsh<CR>", "alises" },
  e = { ":e ~/.zsh/exports.zsh<CR>", "exports" },
  s = { ":e ~/.zsh/secrets.zsh<CR>", "exports" },
  o = { ":e ~/.zsh/opts.zsh<CR>", "exports" },
  f = { ":e ~/.zsh/fn.zsh<CR>", "exports" },
  F = { ":e ~/.zsh/fzf.zsh<CR>", "exports" },
  x = { ":e ~/.zsh/scripts.zsh<CR>", "exports" },
  -- z = { ":e ~/.zshrc<CR>", "zshrc" },
  b = { ":e ~/.zsh/bindings.zsh<CR>", "exports" },
  O = { ":e ~/.zsh/overrides.zsh<CR>", "overrides" },
}
