-- use the same configuration you would use for `vim.lsp.diagnostic.on_publish_diagnostics`.
-- require('lsp_extensions.workspace.diagnostic').set_qf_list()
-- vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
--   require('lsp_extensions.workspace.diagnostic').handler, {
--     signs = {
--       severity_limit = "Error",
--     }
--   }
-- )

-- diagnostics
-- vim.diagnostic.config({
--     underline = true,
--     float = {
--         source = "always",
--     },
--     severity_sort = true,
--     virtual_text = {
--       prefix = "»",
--       spacing = 4,
--     },
--     signs = true,
--     update_in_insert = false,
-- })

-- require("trouble").setup{
  -- icons=true,
-- }
