local o = { noremap = true, silent = true, }
-- Mappings.
-- See `:help vim.lsp.*` for documentation on any of the below functions
local imap = function(k, v, opt) return vim.api.nvim_set_keymap("i", k, v, opt)
end
local nmap = function(k, v, opt) return vim.api.nvim_set_keymap("n", k, v, opt)
end

nmap(',s', '<cmd>lua vim.diagnostic.setloclist()<CR>', { noremap = true, silent = true })
nmap(',a', '<ESC>:CodeActionMenu<CR>', o)
nmap(',h', '<cmd>lua vim.lsp.buf.hover()<CR>', o)
nmap(',o', '<Cmd>lua vim.diagnostic.open_float()<CR>', { noremap = true })
nmap(',R', '<Cmd>lua vim.lsp.buf.rename()<CR>', { noremap = true })

imap('<c-z>', '<Cmd>lua vim.lsp.buf.signature_help()<CR>', o)
nmap('gl', '<cmd>lua vim.lsp.buf.declaration()<CR>', o)
nmap('gd', '<cmd>lua vim.lsp.buf.definition()<CR>', o)
nmap('ga', '<cmd>lua vim.lsp.buf.code_action()<CR>', o)
nmap('g-', '<Cmd>lua vim.diagnostic.open_float()<CR>', { noremap = true })
nmap('g=', '<cmd>lua vim.lsp.buf.signature_help()<CR>', o)
nmap('gh', '<cmd>lua vim.lsp.buf.hover()<CR>', o)
nmap('gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', o)
nmap('gr', '<cmd>lua vim.lsp.buf.references()<CR>', o)
nmap('gR', '<cmd>TroubleToggle lsp_references<CR>', o)
nmap('gD', '<cmd>TroubleToggle lsp_definitions<CR>', o)
nmap('gI', '<cmd>TroubleToggle lsp_implementations<CR>', o)
nmap('gs', '<cmd>lua vim.lsp.buf.document_symbol()<CR>', o)
nmap('gS', '<cmd>lua vim.lsp.buf.workspace_symbol()<CR>', o)
nmap('<space>ca', '<ESC>:CodeActionMenu<CR>', o)
nmap('c<CR>', '<ESC>:CodeActionMenu<CR>', o)
nmap('gy', '<cmd>lua vim.lsp.buf.type_definition()<CR>', o)
imap('<C-x>', '<Cmd>lua vim.lsp.buf.signature_help()<CR>', o)
nmap('<S-Tab>', '<Cmd>lua vim.diagnostic.goto_prev()<CR>', { noremap = true })
nmap('<Tab>', '<Cmd>lua vim.diagnostic.goto_next()<CR>', { noremap = true })
nmap('<space>rn', '<Cmd>lua vim.lsp.buf.rename()<CR>', { noremap = true })
nmap('<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', o)
nmap('<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', o)
nmap('<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', o)
nmap('<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', o)
nmap('<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', o)
nmap('<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', o)
nmap('gr', '<cmd>lua vim.lsp.buf.references()<CR>', o)
nmap('<space>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', o)
nmap('<leader>Wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', o)
nmap('<leader>Wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', o)
nmap('<leader>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', o)
