local function nm(k, c, o) vim.keymap.set({"n"}, k, c, o) end

nm(",fh", "<ESC>:Telescope oldfiles<CR>", { noremap = true, silent = true, nowait = true })
nm(",fb", "<ESC>:Telescope buffers<CR>", { noremap = true, silent = true, nowait = true })
nm(",fH", "<ESC>:Telescope help_tags<CR>", { noremap = true, silent = true, nowait = true })
nm(",fM", "<ESC>:Telescope man_pages<CR>", { noremap = true, silent = true, nowait = true })
nm(",fk", "<ESC>:Telescope keymaps<CR>", { noremap = true, silent = true, nowait = true })
nm(",f<TAB>", "<ESC>:Telescope reloader<CR>", { noremap = true, silent = true, nowait = true })
nm(",f<BS>", "<ESC>:Telescope resume<CR>", { noremap = true, silent = true, nowait = true })
nm(",fG", "<ESC>:Telescope grep_string<CR>", { noremap = true, silent = true, nowait = true })
nm(",fp", "<ESC>:Telescope projects<CR>", { noremap = true, silent = true, nowait = true })
nm(",fz", "<ESC>:Telescope current_buffer_fuzzy_find<CR>", { noremap = true, silent = true, nowait = true })
nm(",Ft", "<ESC>:Telescope tagstack<CR>", { noremap = true, silent = true, nowait = true })
nm(",fT", "<ESC>:Telescope treesitter<CR>", { noremap = true, silent = true, nowait = true })
nm(",f,", "<ESC>:Telescope file_browser<CR>", { noremap = true, silent = true, nowait = true })
nm(",fd", "<ESC>:Telescope diagnostics<CR>", { noremap = true, silent = true, nowait = true })
nm(",fo", "<ESC>:Telescope vim_options<CR>", { noremap = true, silent = true, nowait = true })
nm(",fs", "<ESC>:Telescope symbols<CR>", { noremap = true, silent = true, nowait = true })
nm(",fg", "<ESC>:Telescope grep_string<CR>", { noremap = true, silent = true, nowait = true })
nm(",f<space>", "<ESC>:Telescope live_grep<CR>", { noremap = true, silent = true, nowait = true })
nm(",,,", "<ESC>:Telescope pickers<CR>", { noremap = true, silent = true, nowait = true })
nm(",fB", "<ESC>:Telescope builtin<CR>", { noremap = true, silent = true, nowait = true })
nm(",f<CR>", "<ESC>:Telescope lsp_code_actions<CR>", { noremap = true, silent = true, nowait = true })
nm(",fR", "<ESC>:Telescope lsp_references<CR>", { noremap = true, silent = true, nowait = true })
nm(",f-", "<ESC>:Telescope lsp_dynamic_workspace_symbols<CR>", { noremap = true, silent = true, nowait = true })
nm(",fO", "<ESC>:Telescope colorscheme<CR>", { noremap = true, silent = true, nowait = true })
nm(",fs", "<ESC>:Telescope lsp_document_symbols<CR>", { noremap = true, silent = true, nowait = true })
nm(",fS", "<ESC>:Telescope lsp_workspace_symbols<CR>", { noremap = true, silent = true, nowait = true })
nm(",fY", "<ESC>:Telescope symbols<CR>", { noremap = true, silent = true, nowait = true })
nm(",fI", "<ESC>:Telescope lsp_implementations<CR>", { noremap = true, silent = true, nowait = true })
nm(",fL", "<ESC>:Telescope lsp_definitions<CR>", { noremap = true, silent = true, nowait = true })
nm(",fr", "<ESC>:Telescope registers<CR>", { noremap = true, silent = true, nowait = true })
nm(",fy", "<ESC>:Telescope lsp_type_definitions<CR>", { noremap = true, silent = true, nowait = true })
nm(",fc", "<ESC>:Telescope commands<CR>", { noremap = true, silent = true, nowait = true })
nm(",fF", "<ESC>:Telescope fd<CR>", { noremap = true, silent = true, nowait = true })
nm(",ft", "<ESC>:Telescope tags<CR>", { noremap = true, silent = true, nowait = true })
nm(",ff", "<ESC>:Telescope find_files<CR>", { noremap = true, silent = true, nowait = true })
nm(",fw", "<ESC>:Telescope live_grep search_dirs={os.getenv('WIKI')} <cr>", { noremap = true, silent = true })
