local M = {}
M.icons = {
  locker = "", -- #f023
  page = "☰", -- 2630
  line_number = "", -- e0a1
  connected = "", -- f817
  dos = "", -- e70f
  unix = "", -- f17c
  mac = "", -- f179
  mathematical_L = "𝑳",
  vertical_bar = "┃",
  vertical_bar_thin = "│",
  left = "",
  right = "",
  block = "█",
  left_filled = "",
  right_filled = "",
  slant_left = "",
  slant_left_thin = "",
  slant_right = "",
  slant_right_thin = "",
  slant_left_2 = "",
  slant_left_2_thin = "",
  slant_right_2 = "",
  slant_right_2_thin = "",
  left_rounded = "",
  left_rounded_thin = "",
  right_rounded = "",
  right_rounded_thin = "",
  circle = "●",
}

M.icon_etc = {
  CLASS = "",
  CLASS_TYPE_ALIAS = "",
  COMPILATION_UNIT = "ﴒ",
  CONSTRUCTOR = "",
  CONSTRUCTOR_INVOCATION = "",
  ENUM = "טּ",
  ENUM_CONSTANT = "יּ",
  EXTENSION = "",
  FIELD = "ﬧ",
  FILE = "",
  FUNCTION = "",
  FUNCTION_INVOCATION = "",
  FUNCTION_TYPE_ALIAS = "",
  GETTER = "",
  LABEL = "",
  LIBRARY = "",
  LOCAL_VARIABLE = "",
  METHOD = "",
  MIXIN = "ﭚ",
  PARAMETER = "",
  PREFIX = "並",
  SETTER = "",
  TOP_LEVEL_VARIABLE = "ﬢ",
  TYPE_PARAMETER = "",
  UNIT_TEST_GROUP = "﬽",
  UNIT_TEST_TEST = "",
  UNKNOWN = "",
}

M.src_icons = {
  buffer                   = "",
  calc                     = "",
  luasnip                  = "",
  nvim_lsp                 = "",
  path                     = "",
  vsnip                    = "",
  crates                   = "",
  dadbod                   = "", -- 
  nvim_lua                 = "",
  orgmode                  = "ﴒ",
  neorg                    = "ﯟ",
  treesitter               = "",
  copilot                  = "ﲀ",
  nvim_lsp_signature_help  = "", -- פּ
  nvim_lsp_document_symbol = "ﭨ",
  vimwiki_tags             = "", --   
  cmp_git                  = "",
  latex_symbols            = "",
  cmdline                  = "", -- 
  npm                      = "",
  cmdline_history          = "",
  cmp_tabnine              = "", -- 
  emoji                    = "並",
}
M.kind_icons = {
  Text          = "",
  Method        = "",
  Function      = "",
  Constructor   = "",
  Field         = "ﰠ",
  Namespace     = "ﲀ",
  Variable      = "",
  Class         = "",
  Interface     = "",
  Module        = "",
  Property      = "",
  Unit          = "",
  Value         = "",
  Enum          = "練",
  Keyword       = "",
  Snippet       = "",
  Color         = "",
  File          = "",
  Object        = " ",
  Key           = "",
  Package       = "",
  Null          = "ﰮ",
  Reference     = "", -- 
  Folder        = "",
  Constant      = "",
  Struct        = "",
  Event         = "",
  Array         = " ",
  Operator      = "",
  EnumMember    = "",
  TypeParameter = "",
  Directory     = "", -- 
  Tag           = "",
}
M.alticons = {
  Class = " ",
  Color = " ",
  Constant = " ",
  Constructor = " ",
  Enum = "了 ",
  EnumMember = " ",
  Field = " ",
  File = " ",
  Folder = " ",
  Function = " ",
  Interface = "ﰮ ",
  Keyword = " ",
  Method = "ƒ ",
  Module = " ",
  Property = " ",
  Snippet = "﬌ ",
  Struct = " ",
  Text = " ",
  Unit = " ",
  Value = " ",
  Variable = " ",
}

M.glpyphs = {
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '﵂',
    '',  '',  '',  '',  '',  '',  '',
    'λ',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',
    '',  '',  '',  '',  '',  ''
}
return M
